#!/bin/sh
node Backend/Ingestion/ingest.js
psql $BACKEND_DATABASE_URL < Database/Scripts/UPDATE_TEAM_CONFERENCES.sql
psql $BACKEND_DATABASE_URL < Database/Scripts/UPDATE_TEAM_LOGO_FILES.sql
psql $BACKEND_DATABASE_URL < Database/Scripts/UPDATE_SCHEDULED_IND.sql
psql $BACKEND_DATABASE_URL < Database/Scripts/UPDATE_WIN_LOSS_RECORDS.sql
node Backend/Processing/calculateRankings.js
