DROP TABLE league CASCADE;
DROP TABLE season CASCADE;
DROP TABLE conference CASCADE;
DROP TABLE team CASCADE;
DROP TABLE score CASCADE;
DROP TABLE rank CASCADE;
DROP TABLE prediction CASCADE;
DROP TABLE ranking_source CASCADE;